vim.g.mapleader = ","

vim.keymap.set('n', '<c-z>'    , '')
vim.keymap.set('n', '<c-Z>'    , '')
vim.keymap.set('n', '<Leader>f', ':ls<CR>:b ')
vim.keymap.set('n', '<Leader>n', ':noh<CR>')
vim.keymap.set('n', '<Leader>w', ':wa<CR>')
vim.keymap.set('n', '<Leader>q', ':qa<CR>')
vim.keymap.set('n', '<Leader>t', ':b term<CR>')
vim.keymap.set('n', '<Leader>a', ':Tabularize ')
vim.keymap.set('v', '<Leader>a', ':Tabularize ')
vim.keymap.set('i', '<Up>'     , '')
vim.keymap.set('i', '<Down>'   , '')
vim.keymap.set('i', '<Left>'   , '')
vim.keymap.set('i', '<Right>'  , '')
vim.keymap.set('n', '<Up>'     , '<C-w>k')
vim.keymap.set('n', '<Down>'   , '<C-w>j')
vim.keymap.set('n', '<Left>'   , '<C-w>h')
vim.keymap.set('n', '<Right>'  , '<C-w>l')
vim.keymap.set('t', '<c-e>'    , '<c-\\><c-n>')
